[package]
name = "isogon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec = "1.0.1"
bpaf = "0.9.6"
lasso = "0.7.2"
nom = "7.1.3"
peg = "0.8.2"
unicode-width = "0.1.11"
