fn_single_line = true
group_imports = "StdExternalCrate"
hard_tabs = true
tab_spaces = 3
imports_granularity = "Crate"
newline_style = "Unix"
max_width = 110
use_small_heuristics = "Max"
match_arm_blocks = false
